// TEST: compilation_should_fail '5:17: ошибка: Функция используется, но нигде не определена: foo'

include "../include/test_env.qdi";

int foo(int x);

int bar(int x) of
	return foo(x) + 1;
end

termination_status main() of
	put_int(bar(0));
	return 0;
end
